services:
  cassandra:
    image: cassandra:latest
    container_name: sql-translator-cassandra
    ports:
      - "9042:9042"
    environment:
      - CASSANDRA_CLUSTER_NAME=SqlTranslatorCluster
      # Added from working example for proper startup
      - CASSANDRA_DC=datacenter1
      - CASSANDRA_RACK=rack1
      - CASSANDRA_ENDPOINT_SNITCH=SimpleSnitch
      # Your desired authentication settings
      - CASSANDRA_AUTHENTICATOR=PasswordAuthenticator
      - CASSANDRA_AUTHORIZER=CassandraAuthorizer
      - CASSANDRA_USER=cassandra
      - CASSANDRA_PASSWORD=cassandra
    volumes:
      - cassandra-data:/var/lib/cassandra
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  cassandra-data: